Repository googleapis/java-cloud-bom, pull requests merged in 2020-12, with the labels that each got.

#1273 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full

#1334 chore: update README
  README.md
Labels: automerge, cla: yes

#1368 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1386 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full, merge
