Repository googleapis/java-cloud-bom, pull requests merged in 2020-08, with the labels that each got.

#748 deps: use dependencyGraphBuilder.buildFullDependencyGraph
  dashboard/pom.xml
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactCache.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactInfo.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactResults.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/ArtifactProblem.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/Artifacts.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/BanOptionalDependencySelector.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/Bom.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/CycleBreakerGraphTransformer.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyGraph.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyGraphBuilder.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyLister.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyPath.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyTreeFormatter.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyTreePrinter.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DirectReport.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/FilteringZipDependencySelector.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/InvalidClassFileProblem.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/ManagedDependencyLister.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/MavenRepositoryException.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/NonTestDependencySelector.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/OsProperties.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/RepositoryUtility.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/UniquePathRecordingDependencyVisitor.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/UnresolvableArtifactProblem.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/Update.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/UpdateReport.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/VersionComparator.java
Labels: automerge, cla: yes

#758 cleanup: removes unused kokoro config files
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#764 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#763 chore: remove auto-approve for google-cloud dependency updates
  .github/workflows/auto-approve.yaml
Labels: cla: yes

#802 feat!: remove google-cloud-irm
  pom.xml
Labels: cla: yes

#819 chore: release 0.132.1-SNAPSHOT
  pom.xml
  versions.txt
Labels: automerge, cla: yes, type: process

#820 deps: update dependency com.google.api.grpc:proto-google-iam-v1 to v1.0.0 and google-cloud-core to v1.93.8
  pom.xml
Labels: cla: yes

#834 docs: adverbs are weak; omit needless words
  README.md
Labels: cla: yes

#803 feat: dashboard search additions, all versions page, stylistic changes
  dashboard/README.md
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/VersionData.java
  dashboard/src/main/resources/css/dashboard.css
  dashboard/src/main/resources/templates/index.ftl
Labels: automerge, cla: yes

#843 feat: dashboard updates
  dashboard/src/main/resources/css/dashboard.css
  dashboard/src/main/resources/templates/index.ftl
Labels: cla: yes

#846 chore: exclude samples lint checks
  synth.py
Labels: cla: yes

#853 fix: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#857 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full
