Repository googleapis/java-cloud-bom, pull requests merged in 2020-03, with the labels that each got.

#410 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  synth.metadata
Labels: automerge, cla: yes

#419 samples: scaffold pom.xml files
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.metadata
Labels: automerge, cla: yes

#420 samples: fix snippet closing tag
  samples/install-without-bom/pom.xml
Labels: automerge, cla: yes

#421 chore: use java helper for templates
  synth.py
Labels: cla: yes

#427 chore: skip samples directory
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.py
Labels: automerge, cla: yes

#425 feat: add billing client
  pom.xml
Labels: automerge, cla: yes, kokoro:force-run

#429 feat: add servicedirectory client
  pom.xml
Labels: automerge, cla: yes, kokoro:force-run

#426 feat: add memcache client
  pom.xml
Labels: automerge, cla: yes

#430 feat: add document-ai client
  pom.xml
Labels: automerge, cla: yes

#424 feat: add accessapproval client
  pom.xml
Labels: automerge, cla: yes

#428 feat: add mediatranslation client
  pom.xml
Labels: automerge, cla: yes

#431 feat: add monitoring-dashboard client
  pom.xml
Labels: automerge, cla: yes

#438 chore: enable context aware commits
  synth.py
Labels: automerge, cla: yes

#446 chore: update common templates
  .kokoro/build.sh
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/linkage-monitor.sh
  renovate.json
  synth.metadata
Labels: automerge, cla: yes

#442 chore: drop alpha version from release tag
  versions.txt
Labels: cla: yes
