Repository googleapis/java-cloud-bom, pull requests merged in 2020-04, with the labels that each got.

#517 chore: update common templates
  .kokoro/common.sh
  .kokoro/nightly/integration.cfg
  synth.metadata
Labels: automerge, cla: yes

#533 chore: release 0.124.0
  CHANGELOG.md
  README.md
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes

#537 chore: update common templates
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  synth.metadata
Labels: automerge, cla: yes

#542 chore: use bom versioning strategy for releases
  .github/release-please.yml
  synth.py
Labels: cla: yes

#567 chore: release 0.125.0
  CHANGELOG.md
  README.md
  pom.xml
  versions.txt
Labels: autorelease: pending, cla: yes
