Repository googleapis/java-cloud-bom, pull requests merged in 2020-07, with the labels that each got.

#700 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#730 feat: add dashboard for shared dependency version checking
  .kokoro/nightly/dashboard.cfg
  .kokoro/nightly/dashboard.sh
  dashboard/README.md
  dashboard/pom.xml
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactCache.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactInfo.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactResults.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardArguments.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
  dashboard/src/main/resources/css/dashboard.css
  dashboard/src/main/resources/js/dashboard.js
  dashboard/src/main/resources/poms/demo.xml
  dashboard/src/main/resources/templates/index.ftl
  dashboard/src/main/resources/templates/macros.ftl
  dashboard/src/main/resources/templates/version_index.ftl
Labels: cla: yes

#737 fix: "Could not find artifact com.google.cloud.tools:dependencies-parent:pom:1.4.4-SNAPSHOT" in dashboard
  .kokoro/nightly/dashboard.sh
  dashboard/pom.xml
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactCache.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactInfo.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactResults.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/ArtifactProblem.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/Artifacts.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/BanOptionalDependencySelector.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/Bom.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/CycleBreakerGraphTransformer.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyGraph.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyGraphBuilder.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyLister.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyPath.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyTreeFormatter.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DependencyTreePrinter.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/DirectReport.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/FilteringZipDependencySelector.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/InvalidClassFileProblem.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/ManagedDependencyLister.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/MavenRepositoryException.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/NonTestDependencySelector.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/OsProperties.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/RepositoryUtility.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/UniquePathRecordingDependencyVisitor.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/UnresolvableArtifactProblem.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/Update.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/UpdateReport.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/dependencies/VersionComparator.java
  dashboard/src/main/resources/templates/index.ftl
Labels: cla: yes

#740 feat: add search bar and dropdown for dashboard, remove index page
  dashboard/README.md
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
  dashboard/src/main/resources/css/dashboard.css
  dashboard/src/main/resources/templates/index.ftl
  dashboard/src/main/resources/templates/version_index.ftl
Labels: cla: yes

#736 deps!: remove google-cloud-gameservices from bom
  pom.xml
Labels: cla: yes

#746 chore: auto-approve renovate PRs to update cloud client library artifacts
  .github/auto-approve.yaml
Labels: automerge, cla: yes

#745 chore: specify repo settings overrides in local configuration
  .github/sync-repo-settings.yaml
Labels: cla: yes

#751 chore: put auto-approve workflow in correct folder
  .github/workflows/auto-approve.yaml
Labels: automerge, cla: yes

#752 chore: fix comment in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#753 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
