Repository googleapis/java-cloud-bom, pull requests merged in 2020-10, with the labels that each got.

#989 feat!: remove common dependencies from google-cloud-bom
  pom.xml
Labels: cla: yes

#1000 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1038 ci(java): restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1040 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1050 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1054 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#1066 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#1075 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1083 feat: add google-cloud-os-config API
  pom.xml
Labels: automerge, cla: yes

#1081 feat: add google-cloud-functions
  pom.xml
Labels: automerge, cla: yes

#1082 feat: add google-cloud-game-servers API
  pom.xml
Labels: automerge, cla: yes
