Repository googleapis/java-cloud-bom, pull requests merged in 2020-11, with the labels that each got.

#1095 feat: add google-cloud-bigqueryconnection API
  pom.xml
Labels: cla: yes

#1094 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1096 feat: add google-cloud-bigqueryreservation API
  pom.xml
Labels: automerge, cla: yes

#1147 fix: version from properties
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java
Labels: cla: yes

#1136 build: run bom-upper-bounds check on GitHub actions
  .github/sync-repo-settings.yaml
  .github/trusted-contribution.yml
  .github/workflows/bom-upper-bounds.yaml
  synth.py
Labels: cla: yes

#1152 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1156 fix: version from release
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java
Labels: cla: yes

#1157 fix: dashboard exclude google-cloud-firestore-admin
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
Labels: cla: yes

#1159 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1177 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#847 feat: dashboard updates - sort by Maven version conventions, add comments, format code
  dashboard/src/main/resources/js/dashboard.js
  dashboard/src/main/resources/templates/index.ftl
Labels: cla: yes

#1238 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: cla: yes, context: full

#1246 ci: disable autorelease in this repo
  .github/workflows/auto-release.yaml
  synth.py
Labels: automerge, cla: yes

#1248 fix: dashboard column checking for sorting by Maven version
  dashboard/src/main/resources/js/dashboard.js
Labels: cla: yes

#1253 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1257 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: automerge, cla: yes, context: full, samples
