Repository googleapis/java-cloud-bom, pull requests merged in 2021-09, with the labels that each got.

#2697 chore: enable release-trigger bot
  .github/release-trigger.yml
  synth.metadata
Labels: cla: yes, context: partial

#2786 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  renovate.json
  synth.metadata
Labels: cla: yes, context: partial

#2813 chore(java): update windows build
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#2814 chore: use release-please to tag releases
  .github/release-please.yml
Labels: cla: yes, automerge

#2819 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: kokoro:force-run, cla: yes, automerge

#2820 chore: re-generated to pick up changes from self
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, context: none

#2827 chore(java): update shared-config and shared-dependencies version in pom template
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#2996 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, automerge

#2997 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
  owlbot.py
Labels: cla: yes

#3039 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#3046 chore: change branch master to main in github configurations
  README.md
Labels: cla: yes, automerge
