Repository googleapis/java-cloud-bom, pull requests merged in 2021-08, with the labels that each got.

#2402 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes

#2403 chore: configure initial java7 version
  .github/workflows/ci.yaml
  .github/workflows/dashboard.yaml
  .github/workflows/full-convergence-check.yaml
Labels: cla: yes, automerge

#2392 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, automerge, context: full

#2482 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes

#2552 chore: remove grpc-gcp from google-cloud-bom
  pom.xml
Labels: cla: yes, automerge

#2561 deps: update dependency com.google.cloud:google-cloud-pubsub to v1.113.9
  pom.xml
Labels: cla: yes, automerge

#2546 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: kokoro:force-run, cla: yes, automerge, context: full

#2689 chore: remove linkage monitor check
  .github/sync-repo-settings.yaml
  .github/workflows/ci.yaml
Labels: cla: yes

#2721 feat: add google-cloud-debugger-client
  pom.xml
Labels: cla: yes, automerge
