Repository googleapis/java-cloud-bom, pull requests merged in 2021-04, with the labels that each got.

#1781 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1845 chore: fix typo
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1850 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1852 feat: update google cloud bom with new GA libraries
  pom.xml
Labels: cla: yes

#1932 chore: fix ResourceManager dependency
  pom.xml
Labels: automerge, cla: yes
