Repository googleapis/java-cloud-bom, pull requests merged in 2021-03, with the labels that each got.

#1658 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1660 fix: omit download progress from build logs
  .kokoro/bom-upper-bounds-check.sh
Labels: cla: yes

#1666 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1665 chore: clean up dashboard dependencies
  dashboard/pom.xml
Labels: cla: yes

#1747 chore: add back needed dashboard dependencies
  dashboard/pom.xml
Labels: automerge, cla: yes

#1749 ci: add Github Actions workflow for dashboard
  .github/workflows/dashboard.yaml
  .kokoro/dashboard.sh
Labels: automerge, cla: yes

#1753 ci: update dashboard.sh to executable
  .kokoro/dashboard.sh
Labels: automerge, cla: yes

#1752 ci: add Github Actions workflow to check convergence in a release PR
  .github/workflows/dashboard.yaml
  .kokoro/dashboard.sh
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardArguments.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
Labels: automerge, cla: yes

#1760 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: automerge, build.sh, cla: yes, context: full, in, sample-secrets, samples

#1761 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
