Repository googleapis/java-cloud-bom, pull requests merged in 2021-02, with the labels that each got.

#1456 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes

#1461 chore: remove leading newline from LICENSE
  LICENSE
  synth.metadata
Labels: cla: yes, context: full

#1462 fix: update repo name
  .kokoro/release/publish_javadoc11.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#1495 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#1499 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1502 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1504 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1569 deps: update google-cloud-compute to 0.119.4-alpha
  pom.xml
Labels: automerge, cla: yes

#1543 dashboard: add option to print report to stdout
  dashboard/README.md
  dashboard/pom.xml
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactCache.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactInfo.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactResults.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardArguments.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/VersionData.java
Labels: cla: yes
