Repository googleapis/java-cloud-bom, pull requests merged in 2021-06, with the labels that each got.

#2095 feat: add Service Management API and Dataproc Metastore to Google Cloud Bom
  dependency-convergence/pom.xml
  pom.xml
Labels: cla: yes

#2096 feat: add Workflows to Google Cloud BOM
  dependency-convergence/pom.xml
  pom.xml
Labels: cla: yes

#2094 build: switch all clients to use the google endpoint on sonatype
  pom.xml
Labels: automerge, cla: yes

#2142 chore: fix dependencies
  dependency-convergence/pom.xml
Labels: automerge, cla: yes

#2234 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#2262 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#2259 chore: remove proto-google-cloud-firestore-bundle-v1 from dashboard table
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/DashboardMain.java
Labels: cla: yes

#1942 ci: deleting upper-bounds check
  .github/workflows/bom-upper-bounds.yaml
  .kokoro/bom-upper-bounds-check.sh
  .kokoro/presubmit/bom-upper-bounds.cfg
Labels: cla: yes

#2263 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#2278 chore: point to new compute dependency
  dependency-convergence/pom.xml
  pom.xml
Labels: automerge, cla: yes
