Repository googleapis/java-cloud-bom, pull requests merged in 2021-05, with the labels that each got.

#1941 ci: removing upper bounds check from required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes

#1946 feat: add api-gateway and cloud profiler to google cloud bom
  pom.xml
Labels: automerge, cla: yes

#1948 ci: add full dependency convergence check
  .github/workflows/full-convergence-check.yaml
  dependency-convergence/pom.xml
Labels: automerge, cla: yes

#1960 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: full

#2016 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#2052 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#2062 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#2072 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
