Repository googleapis/java-cloud-bom, pull requests merged in 2022-05, with the labels that each got.

#4322 chore: setting up manifest for Release Please to generate 1 PR for 2 BOMs
  .github/release-please.yml
  .release-please-manifest.json
  google-cloud-bom/pom.xml
  google-cloud-bom/versions.txt
  libraries-bom/versions.txt
  release-please-config.json
  tests/src/test/java/com/google/cloud/BomContentTest.java
Labels: size: s

#4422 build: try to enable maven-workspace plugin
  release-please-config.json
Labels: size: xs

#4284 feat: add google-cloud-dataplex to GCB
  pom.xml
  tests/dependency-convergence/pom.xml
Labels: automerge, size: l

#4448 deps(libraries-bom): use library versions from the shared dependencies BOM 2.12.0
  libraries-bom/pom.xml
  owlbot.py
  renovate.json
Labels: size: s

#4449 ci: test directory version upgrade
  tests/dependency-convergence/pom.xml
Labels: size: xs

#4462 fix: the root pom should not have dependencyManagement any more
  google-cloud-bom/pom.xml
  pom.xml
Labels: size: l

#4464 ci: bom-content-test as required. libraries-bom to use snapshot
  .github/sync-repo-settings.yaml
  libraries-bom/pom.xml
Labels: size: xs
