Repository googleapis/java-cloud-bom, pull requests merged in 2022-08, with the labels that each got.

#4773 build: use x-version-update-start in tests module
  tests/dependency-convergence/pom.xml
Labels: automerge, size: xs

#4771 build: Release Please to control tests module too
  release-please-config.json
Labels: automerge, size: xs

#4786 ci: reverting the marker in tests
  tests/dependency-convergence/pom.xml
Labels: size: xs

#4785 docs: explaining users to use the Libraries BOM
  README.md
  google-cloud-bom/README.md
Labels: size: m

#4787 chore: Adding "tests/dependency-convergence" module to release please config
  .release-please-manifest.json
  release-please-config.json
  tests/dependency-convergence/pom.xml
  tests/dependency-convergence/versions.txt
Labels: size: s

#4789 chore: removing tests from manifest config
  .release-please-manifest.json
  release-please-config.json
  tests/dependency-convergence/pom.xml
Labels: size: s

#4893 deps: java-shared-dependencies 3.0.1 and using gax-bom
  libraries-bom/pom.xml
Labels: size: s

#4772 test: assert convergence among Cloud Java client libraries
  .github/workflows/full-convergence-check.yaml
  tests/pom.xml
  tests/src/test/java/com/google/cloud/BomContentAssertionsTest.java
  tests/src/test/java/com/google/cloud/BomContentTest.java
Labels: size: m

#4925 ci: skip-github-release for the "tests/dependency-convergence" module
  release-please-config.json
Labels: size: xs

#4964 fix: touching libraries-bom/pom.xml
  libraries-bom/pom.xml
Labels: size: xs
