Repository googleapis/java-cloud-bom, pull requests merged in 2023-07, with the labels that each got.

#6099 deps: update dependency com.google.cloud:google-cloud-storage-bom to 2.22.6
  google-cloud-bom/pom.xml
Labels: size: xs

#6083 feat: add table of modules for a libraries-bom version to README
  .github/workflows/update-readme-table.yaml
  README.md
  libraries-bom-table-generation/javaModulesMetadata.yaml
  libraries-bom-table-generation/updateREADMETable.py
  libraries-bom/pom.xml
Labels: size: l

#6106 chore: update README table workflow to be able to be manually triggered
  .github/workflows/update-readme-table.yaml
Labels: size: xs

#6107 chore: add pyyaml installation step to workflow
  .github/workflows/update-readme-table.yaml
Labels: size: xs

#6109 chore: update workflow to use branch instead of main
  .github/workflows/update-readme-table.yaml
Labels: size: xs

#6117 chore: update workflow to generate PRs with correct commit prefix and use Cloud Java bot
  .github/workflows/update-readme-table.yaml
Labels: size: s

#6120 chore: update workflow to clean up branch
  .github/workflows/update-readme-table.yaml
Labels: size: xs

#6122 chore: update workflow to use GH_TOKEN instead of GITHUB_TOKEN
  .github/workflows/update-readme-table.yaml
Labels: size: xs

#6126 chore: fix branch name in workflow
  .github/workflows/update-readme-table.yaml
Labels: size: xs

#6128 chore: Add dependencies(17) as the only required check
  .github/sync-repo-settings.yaml
Labels: size: xs
