Repository googleapis/java-cloud-bom, pull requests merged in 2023-01, with the labels that each got.

#5709 chore: Release as version 26.3.0
  .kokoro/requirements.txt
  libraries-bom/pom.xml
Labels: size: m

#5716 fix: release note script to handle GITHUB_REF properly
  .github/workflows/release-note-generation.yaml
Labels: size: xs

#5718 chore: preparing 26.1.x branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#5719 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/dashboard.yaml
  .github/workflows/full-convergence-check.yaml
Labels: size: l

#5722 chore: exclude requirement.txt in renovate.json
  renovate.json
Labels: size: xs

#5721 deps: overriding gax, protobuf, and bigquerystorage to patched versions
  google-cloud-bom/pom.xml
  libraries-bom/pom.xml
Labels: size: s

#5724 ci: install BOMs locally when creating release notes
  .github/workflows/release-note-generation.yaml
Labels: size: xs

#5758 ci: remove the experimental full convergence check
  .github/workflows/full-convergence-check.yaml
  tests/src/test/java/com/google/cloud/BomContentTest.java
Labels: size: s

#5760 chore: Changing release-please setup to single-component
  .github/release-please.yml
  .release-please-manifest.json
  google-cloud-bom/versions.txt
  libraries-bom/versions.txt
  release-please-config.json
  tests/dependency-convergence/versions.txt
  tests/versions.txt
  versions.txt
Labels: size: m

#5761 chore: update release-please config.
  .github/release-please.yml
Labels: size: xs

#5766 chore: fixing release-please configs
  .github/release-please.yml
  versions.txt
Labels: automerge, size: xs

#5769 chore: Using "always-bump-minor" versioning for this release.
  .release-please-manifest.json
  release-please-config.json
Labels: size: s

#5771 chore: update release-please config
  .github/release-please.yml
Labels: size: xs

#5776 chore: Adding annotations to update version in README.md
  README.md
Labels: size: xs

#5782 chore: update release-please config
  release-please-config.json
Labels: size: xs

#5784 deps: Testing README.md release-please update.
  pom.xml
Labels: size: xs

#5786 chore: Changing release type to java-yoshi
  release-please-config.json
Labels: size: xs

#5788 ci: release note generation for single-component setup
  .github/workflows/release-note-generation.yaml
Labels: size: xs

#5789 ci: fixing update release tag in release-note job
  .github/workflows/release-note-generation.yaml
Labels: size: xs
