Repository googleapis/java-cloud-bom, pull requests merged in 2024-05, with the labels that each got.

#6366 test: rename full-convergence-check.yaml to bom-content-test
  .github/workflows/bom-content-test.yaml
Labels: size: s

#6573 chore: Remove obsolete files
  .github/workflows/approve-readme.yaml
  .github/workflows/ci.yaml
  .github/workflows/renovate_config_check.yaml
  .kokoro/release/bump_snapshot.cfg
  .kokoro/release/bump_snapshot.sh
  .kokoro/release/common.cfg
  .kokoro/release/common.sh
  .kokoro/release/drop.cfg
  .kokoro/release/drop.sh
  .kokoro/release/promote.cfg
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/snapshot.cfg
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  .kokoro/requirements.in
  .kokoro/requirements.txt
  owlbot.py
Labels: size: xl

#6564 chore: add check to verify presence of pom url before reading from it
  dashboard/pom.xml
  dashboard/src/main/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenData.java
  dashboard/src/test/java/com/google/cloud/tools/opensource/cloudbomdashboard/ArtifactMavenTest.java
Labels: size: l
