Repository googleapis/java-cloud-bom, pull requests merged in 2024-02, with the labels that each got.

#6410 chore: update bom table readme to exclude bigtable-stats
  libraries-bom-table-generation/javaModulesMetadata.yaml
  libraries-bom-table-generation/updateREADMETable.py
Labels: automerge, size: xs

#6437 fix(libraries-release-data): add service name lookup from artifact id for gapic libraries, add apiary libraries and spring cloud gcp to release data table.
  .kokoro/nightly/create-versions-csv.sh
  .kokoro/nightly/fetch-library-data.sh
  .kokoro/nightly/get-apiary-service-names.sh
  .kokoro/nightly/get-service-names.sh
Labels: size: m

#6442 chore: updating contribution guideline
  CONTRIBUTING.md
  owlbot.py
Labels: size: xs
